[book]
title = "Wez's Terminal Emulator"
author = "Wez Furlong"
src = "."

[build]
build-dir = "../gh_pages"
create-missing = false

[output.html]
additional-css = ["custom.css", "asciinema-player.css"]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/wez/wezterm"
additional-js = ["mermaid.min.js", "mermaid-init.js", "asciinema-player.min.js"]

[output.html.fold]
enable = true
level = 1

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.formatter]
command = "/home/chris/Documents/mdbook-mermaid/target/debug/mdbook-mermaid"
format = ["lua"]


[formatter.lua]
command = "stylua"
